=== atulchune/XmlProject/public/mybookstore.dtd
<!DOCTYPE bookstore [
  <!ELEMENT bookstore (name, topic)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT topic (name, ISBN)>
  <!ELEMENT ISBN (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT book (title, author)>
]>

=== atulchune/XmlProject/Mybookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "mybookstore.dtd">
<bookstore>
  <name>City Bookstore</name>
  <topic>
    <name>Fiction</name>
    <ISBN>978-1234567890</ISBN>
    <book>
      <title>The Great Gatsby</title>
      <author>F. Scott Fitzgerald</author>
    </book>
    <book>
      <title>To Kill a Mockingbird</title>
      <author>Harper Lee</author>
    </book>
  </topic>
  <topic>
    <name>Science</name>
    <ISBN>978-0987654321</ISBN>
    <book>
      <title>A Brief History of Time</title>
      <author>Stephen Hawking</author>
    </book>
  </topic>
</bookstore>
